export const CREATE_AUDIO_CTX = 'CREATE_AUDIO_CTX';
export const CREATE_ANALYSER = 'CREATE_ANALYSER';
export const CREATE_MODULATOR = 'CREATE_MODULATOR';
export const CREATE_CARRIER = 'CREATE_CARRIER';
export const CREATE_MOD_GAIN = 'CREATE_MOD_GAIN';
export const CREATE_MASTER_GAIN = 'CREATE_MASTER_GAIN';
export const SET_ATTACK = 'SET_ATTACK';
export const SET_RELEASE = 'SET_RELEASE';
